name: sendbird_chat_sdk
description: With Sendbird Chat for Flutter, you can easily build an in-app chat with all the essential messaging features.
version: 5.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  uuid: ^4.5.1
  json_annotation: ^4.8.1
  encrypt: ^5.0.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  logger: '>=1.4.0 <3.0.0'
  mime: ^1.0.4
  connectivity_plus: ^6.0.5
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  universal_io: ^2.2.0
  async: ^2.10.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.22.0
  stack_trace: ^1.11.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
